[parity]
chain = "ethereum"
mode = "active"

[rpc]
disable = false
port = 8545
interface = "local"
cors = []
apis = ["web3", "eth", "pubsub", "net", "parity", "parity_pubsub", "traces"]
hosts = ["none"]

#[network]
#min_peers = 25
#max_peers = 50
